version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${DOCKEREO_MONGO_ROOT_PASSWORD:1234}
    ports:
      - 27017:27017
    networks:
      - mongo-network
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DOCKEREO_MONGO_ROOT_PASSWORD:1234}
    networks:
      - mongo-network
    depends_on:
      - mongo
      
networks:
  mongo-network:
    driver: bridge

volumes:
  mongo-data: