# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/mariadb.conf.d/my.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 10180:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - db

volumes:
  mariadb-data: